using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PokemonKotas.Data.Models;

/// <summary>
///     Represents a Pokémon sprite, including its URL and Base64 encoded image data.
///     This class also maintains relationships with captured Pokémon and Pokémon evolutions.
/// </summary>
public class PokemonSprite
{
    /// <summary>
    ///     Gets or sets the unique identifier for the Pokémon sprite.
    /// </summary>
    /// <value>
    ///     The unique identifier for the Pokémon sprite, which is generated by the database.
    /// </value>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    ///     Gets or sets the Base64 encoded image data of the Pokémon sprite.
    /// </summary>
    public string SpriteBase64 { get; set; }

    /// <summary>
    ///     Gets or sets the captured Pokémon associated with this sprite.
    /// </summary>
    /// <remarks>
    ///     This property establishes a relationship between the <see cref="PokemonSprite" /> and the
    ///     <see cref="CapturedPokemon" />
    ///     it belongs to. It is used to navigate from a sprite to the captured Pokémon it represents.
    /// </remarks>
    public virtual CapturedPokemon? CapturedPokemon { get; set; } = null!;

    /// <summary>
    ///     Gets or sets the evolution details associated with this Pokémon sprite.
    ///     This property represents a relationship to the <see cref="PokemonEvolution" /> entity,
    ///     which includes information such as the evolution's name, order, and whether it is legendary or mythical.
    /// </summary>
    public virtual PokemonEvolution? PokemonEvolution { get; set; } = null!;
}